### Config file for preprocessing pipeline
### RE 11/10/2022

prb: PRBATCH
codedir: /projects/ehi/data/0_Code/EHI_bioinformatics_EHI_VERSION/workflow
workdir: /projects/ehi/data/PPR/PRBATCH
logdir: /projects/ehi/data/RUN/PRBATCH/logs

hg_url: HG_URL
hostgenome: HOST_GENOME

adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
